plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.1.21'
    id 'maven-publish'
}

group = 'com.pdlayer'
version = '1.0.1'
description = 'Lightweight Kotlin library for Discord IPC / Rich Presence'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.code.gson:gson:2.11.0'
}

kotlin {
    jvmToolchain(21)
}

java {
    withSourcesJar()
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    compilerOptions {
        freeCompilerArgs.add('-Xjsr305=strict')
    }
}
